### ISSUE TITLE
Bad Request - { "message": "Cannot send an empty message", "code": 50006 }

### ISSUE THREAD

**Issue by heyitsmarlon** [discord-php/DiscordPHP-Http#12] opened 2022-05-02 15:18 UTC
My application was built using DiscordPHP-Http last year and it worked perfectly up until just recently. No changes have been made to the code but since a few days I get the error `Bad Request - { "message": "Cannot send an empty message", "code": 50006 }`.

What could possibly be the issue?

**Comment by SQKo** [comment] 2022-05-23 17:49
Please show your code

**Comment by SQKo** [comment] 2022-06-14 16:22
Duplicate of https://github.com/discord-php/DiscordPHP/issues/797

**Closed as not planned by SQKo** 2022-06-14 16:22 UTC
